version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${EXPOSE_POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 10
      start_period: 10s

  prisma:
    build: .
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "go run github.com/steebchen/prisma-client-go generate && go run github.com/steebchen/prisma-client-go migrate deploy"
    networks:
      - app_network
    env_file:
      - .env

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "${API_PORT}:3000"
    env_file:
      - .env
    networks:
      - app_network

volumes:
  pg_data:

networks:
  app_network:
